name: ML Project
on: [push]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
        
      - name: Install dependencies
        run: |
          pip install mlflow scikit-learn pandas numpy
          
      - name: Create MLflow directory
        run: mkdir -p MLProject/mlruns
          
      - name: Run MLflow project
        run: |
          mlflow run . --env-manager=local
          
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: mlflow_results
          path: MLProject/mlruns
          if-no-files-found: error
          retention-days: 1