name: Train Model
on: [push]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Setup Environment
        run: |
          # Create clean environment
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install scikit-learn==0.24.2 mlflow==1.30.0 pandas==1.2.5

      - name: Run Training
        run: |
          source venv/bin/activate
          mlflow run ./MLProject \
            --env-manager=local \
            --experiment-name="CI_Pipeline"
          
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: mlflow_results
          path: MLProject/mlruns
          if-no-files-found: error
          retention-days: 1