name: Train Model
on: [push]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Install MLflow
        run: pip install mlflow==2.3.1
      
      - name: Run MLflow Project
        run: |
          mlflow run ./MLProject --env-manager=local
          
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: mlflow_results
          path: MLProject/mlruns
          if-no-files-found: error
          retention-days: 1